### ISSUE TITLE
OnJoin stay in channel

### ISSUE THREAD

**Issue by MayhemBill** [samclane/Snake-Cogs#10]
The constant leaving and joining of the bot is quite annoying

**Comment by samclane** [comment]
I agree. I've been doing it because I don't know how to make it play nice with other Audio Cogs, causing the Bot to crash whenever another Cog requires it. 

I'll investigate.

**Comment by samclane** [comment]
@MayhemBill 

The most recent version (686064418c28abc831b9736a520af02543a64ca5) removes the auto-leave. It instead relies on the `emptydisconnect` timer.

**Comment by samclane** [comment]
Can't get this to work on a Raspberry Pi; the first few seconds of speech are always choppy.

**Comment by MayhemBill** [comment]
Let me update the cog and try it out and I'll get back to you.
