### ISSUE TITLE
armorsmith raise Exception is giving an Exception

### ISSUE THREAD

**Issue by ClaireCruz** [samclane/Snake-Cogs#4]
if people are fighting then the raise Exception, is giving me in error in the logs, please help

**Comment by samclane** [comment]
Could you please post the exact error it gives you in the console?

**Comment by ClaireCruz** [comment]
sure

**Comment by ClaireCruz** [comment]
![afbeelding](https://user-images.githubusercontent.com/30986819/32460390-eff84232-c332-11e7-87eb-e202ad12082f.png)

**Comment by ClaireCruz** [comment]
but we just started so idk whats wrong

**Comment by samclane** [comment]
One or more players does not have a weapon equipped. I have added a message to the bot telling users this. Please let me know if equipping a weapon on both players fixes this.

**Comment by ClaireCruz** [comment]
now if i want to restart the cog it says this
![afbeelding](https://user-images.githubusercontent.com/30986819/33049749-c3840972-ce61-11e7-9a23-12a2a94ddb06.png)

**Comment by ShibePrime** [comment]
Error on initial install. 

invalid syntax ... armorsmith.py 620,19 '        \tawait self.bot.say("One or more players does not have a weapon equipped!".format(user.mention))\n'))
' 

I think it may be a formatting issue with leading spaces/tabs 

![armor](https://user-images.githubusercontent.com/16141646/33238601-f5a6be9e-d245-11e7-981d-9a7b5b633217.png)

**Comment by ShibePrime** [comment]
#7 I think I got it, Sorry about the goof up! xD

**Comment by ClaireCruz** [comment]
i still got the syntax problem

**Comment by ClaireCruz** [comment]
:(

**Comment by samclane** [comment]
@ClaireCruz Have you made sure to `[p]cog update`? And have you tried `[p]restart` -ing your bot?

**Comment by samclane** [comment]
@ClaireCruz @therealshibe It seems the function was not async, so the `await` statement was not registering. I fixed it with my latest commit, see if it works.
